Repository dcsaorg/DCSA-OpenAPI, pull requests merged in 2025-03, with the labels that each got.

#502 SD-2048 JIT 2.0: Update error codes in description
  jit/v2/JIT_v2.0.0.yaml
Labels: enhancement

#505 SD-2093: JIT 2.0: Change OPTION -> OPTIONS in Error object
  jit/v2/JIT_v2.0.0.yaml
Labels: Review effort 1/5

#506 SD-1825: CS 1.0: Make CS v1.0.1 candidate
  cs/v1/CS_v1.0.1.yaml
Labels: Review effort 2/5

#507 SD-2095: JIT 2.0: Update What's New for 28 March 2025 publication
  jit/v2/README.md
Labels: Review effort 1/5
